### ISSUE TITLE
Black Glitches

### ISSUE THREAD

**Issue by abn5x** [FocalPaint/FocalPaint#11]
Happens when there is movement in the app or over it:

![Animated GIF-downsized](https://user-images.githubusercontent.com/31189812/101621258-d360e900-3a15-11eb-923d-83cceef13b34.gif)

**Comment by abn5x** [comment]
It seemed to be produced by the canvas texture, as I changed it to another texture, the glitch disappeared, then if I didn't save the change and closed the app and loaded the document again (with the buggy texture) it happened every time.

Now, I changed the another texture, saved, then changed back to the buggy texture and saved again, closed the app and reopened it and the document and the bug is gone, and can't reproduce it again.

**Comment by briend** [comment]
I’m glad it’s not just my device!  Really weird, it usually happens when the canvas is pinched smaller like you do there.  Next time I mean to grab a screen video to see if it actually records.  I’ve been kind of hoping it was a bug in Metal that gets fixed soon

**Comment by briend** [comment]
I think this is finally fixed in today’s release. I changed the filtering to nearest neighbor so that pixels don’t get fuzzy when you zoom in, and I think that also fixed the weird glitchy black streaks.  I hope!
