### ISSUE TITLE
Feature request: export in PNG

### ISSUE THREAD

**Issue by drawingthesun** [FocalPaint/FocalPaint#14]
Feature request: export in PNG

**Comment by briend** [comment]
Thanks for the suggestion!  I've added a menu with a bunch of export options; you can share/export as several formats and quality settings.  There's also sRGB options (in red) in case you are sharing to a website that can't deal with Display P3 wide gamut color.  This will appear it version 2.0.16 in the next day or so, but feel free to reopen this issue if you have any issues or suggestions:

![B1EFA257-FC64-4D2E-A682-CB461AE4D658_1_201_a](https://user-images.githubusercontent.com/6015639/219909811-b0cd5e74-3944-4488-a8a3-0a6dd9c889ca.jpeg)

**Comment by briend** [comment]
You can also try this sooner in Test Flight https://testflight.apple.com/join/1adnuUHv
