### ISSUE TITLE
Possible data loss

### ISSUE THREAD

**Issue by abn5x** [FocalPaint/FocalPaint#6]
Seems that after the update, I lost some saved progress, not all but seems that it didnt auto-save before updating and restored to the last manual save. It would be nice to save the state of the current paintings before updating.

**Comment by briend** [comment]
Sorry about that.  I am planning to add an auto-save feature soon that will save every 5 minutes or so. I tried to make an auto-save when the app goes into the background, but it turns out iOS doesn't really let you do a whole lot of work in the background, so it would actually kill it mid-way through the save process.

**Comment by briend** [comment]
I added a simple auto-save every 5 minutes in v1.34.  Hopefully that is better than nothing for now.  Thanks!

**Comment by abn5x** [comment]
> Sorry about that. I am planning to add an auto-save feature soon that will save every 5 minutes or so. I tried to make an auto-save when the app goes into the background, but it turns out iOS doesn't really let you do a whole lot of work in the background, so it would actually kill it mid-way through the save process.

Naah, don’t worry about the loss, i’m aware that is a beta and things like that are quite frequent.

Anyway your app is incredible, I was following your work on Mypaint’s pigment mode and was wondering if someday it will get to iOS, and you were already working on it when I decided to watch your github hahahah.

Amazing work overall ⚡️⚡️⚡️

**Comment by briend** [comment]
Thank you!  I hope to get this added to MyPaint someday but not sure it will work out with all the other stuff MyPaint can do.  Plus, iPad has Metal GPU :-D

I'll close this and follow up in #8
