### ISSUE TITLE
Delay in getting new updates TestFlight

### ISSUE THREAD

**Issue by abn5x** [FocalPaint/FocalPaint#7]
Whenever you make an update it takes around 12-16 hours before i get the update in Testflight, for example the last 1.3.4v I still didn't get it, I think that's because you submit new versions every time and it's going through review each time. There's a trick to get the new versions instantly to the beta testers explained here, without it needing review:

https://christianselig.com/2020/06/testflight-review/

Basicaly you just change the Build number not the version. Hope this is helpful

**Comment by briend** [comment]
Oh thanks, I will do this with the next build.  I had heard about this but wasn't quite sure there was a delay, since I get notified immediately and I guess because I'm special I get access right away with my own Test Flight on my iPad.  Time to really open the flood gates on builds!

**Comment by briend** [comment]
Just submitted v1.34 Build 2! Hope it gets out quickly this time. Thanks again

**Comment by abn5x** [comment]
> Just submitted v1.34 Build 2! Hope it gets out quickly this time. Thanks again

Effectively, I received it 34 min ago ;) Nice! Now the development process can surely be even faster :3
