### ISSUE TITLE
Brush Engine Ideas

### ISSUE THREAD

**Issue by briend** [FocalPaint/FocalPaint#9]
I am really thinking a node-based brush editor makes the most sense.  Basically drag inputs like Pressure, Tilt, Touch Coordinates, Random Number Generator, Signal Generator, etc and connect them through operators to manipulate the brush settings like Radius, Opacity, Smudge Ratio, XY Coordinates, Color, etc etc.

https://www.youtube.com/watch?v=oq-d6v7yOXk
https://armorpaint.org/manual/img/brush_jitter.jpg
https://www.raywenderlich.com/7705231-creating-a-mind-map-ui-in-swiftui

**Comment by abn5x** [comment]
Seems like a great idea 🙌🏻 Also would love to see for the best UX all the settings should have little icons of “i” when touched should show some tool tips of how the max and min number of the respective settings affect the brush, and somewhere farther in the development a live editable paint stroke would be even better :)

Cheers and nice work as always!
